#!/usr/bin/env python3
"""Build lens/docs/*.html from lens/_build/content.py.

    python3 lens/_build/build.py

No dependencies beyond Python 3. Also writes lens/SCREENSHOTS.md, the worklist
of screenshot slots still waiting for a file.
"""
import os
import sys
import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import engine  # noqa: E402
from engine import PAGE, ICONS, render, SHOTS  # noqa: E402
from content import PAGES, ORDER  # noqa: E402

LENS = os.path.dirname(HERE)
DOCS = os.path.join(LENS, "docs")

# stamp_updated.py overwrites this from the file's last commit date; this is
# only what a freshly built, not-yet-committed page carries.
TODAY = datetime.date.today().strftime("%d %b %Y")


def main():
    os.makedirs(DOCS, exist_ok=True)

    missing = set(PAGES) ^ set(ORDER)
    if missing:
        raise SystemExit("ORDER and PAGES disagree about: %s" % sorted(missing))

    for slug in ORDER:
        page = PAGES[slug]
        body = render(page["blocks"], page["title"])
        html = PAGE.format(
            title=page["title"],
            lede=page["lede"],
            desc=page["desc"],
            updated=TODAY,
            icon=ICONS[page["icon"]],
            body=body,
        )
        path = os.path.join(DOCS, slug + ".html")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(html)
        print("wrote lens/docs/%s.html" % slug)

    write_screenshot_worklist()


def write_screenshot_worklist():
    """Mirrors the format of timesheets/SCREENSHOTS.md so both read the same."""
    have = set(os.listdir(os.path.join(LENS, "assets")))
    outstanding = [s for s in SHOTS if s[0] not in have]

    lines = [
        "# Lens docs — screenshots needed",
        "",
        "%d screenshots. Save each one into `lens/assets/` using the" % len(outstanding),
        "exact filename below. The docs pick them up automatically on the next page",
        "load — until then each slot renders a dashed placeholder naming the file it",
        "wants, so an unshot page looks unfinished rather than broken.",
        "",
        "Generated by `lens/_build/build.py` — do not edit by hand.",
        "",
        "Guidance: capture Chrome at a comfortable window width (about 1440px), use",
        "the dark theme unless the shot is specifically about light mode, and capture",
        "realistic but fictional page content rather than anything confidential —",
        "these end up on a public docs site.",
        "",
    ]

    page = None
    for filename, caption, page_label in SHOTS:
        if page_label != page:
            page = page_label
            lines += ["## %s" % page, ""]
        mark = "x" if filename in have else " "
        lines += ["- [%s] `%s`" % (mark, filename), "      %s" % caption]
    lines.append("")

    with open(os.path.join(LENS, "SCREENSHOTS.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote lens/SCREENSHOTS.md — %d slots, %d still needed"
          % (len(SHOTS), len(outstanding)))


if __name__ == "__main__":
    main()
